### PR TITLE
Update LXD Client Config

### PR DESCRIPTION
**Pull request by jtopjian**
This commit updates the LXD discovery plugin to support the new LXD
client API.

### CODE REVIEW

**Comment by jtopjian** [comment]
Hello,

The LXD project recently refactored their client API. We moved to this new API a few weeks ago in the [Terraform LXD provider](https://github.com/sl1pm4t/terraform-provider-lxd/commit/d32b3a5041299a22df59c4df71ccb04568c8eb49) and can verify the changes are safe and work.

These are all internal changes. There are no changes to the configuration or any other user-facing pieces.

In order to help with testing, I have created a set of Terraform configurations that you can find here:

https://github.com/jtopjian/terraform-gobetween-dev

This will deploy a virtual machine to either AWS or OpenStack and create an environment with LXD (including two running containers), Go, and dependencies. 

To use this, do the following:

1. Download Terraform
2. Clone the above repository
3. Do:

```shell
$ cd terraform-gobetween-dev/aws
$ export AWS_SECRET_ACCESS_KEY=your aws secret access key
$ export AWS_ACCESS_KEY_ID=your aws access key id
$ terraform apply
```

If you prefer not to use Terraform, you can simply use the deploy script found in `files/deploy.sh`. Just copy this to any Ubuntu 16.04 virtual machine.

When the script is done running, you can then build a `gobetween` binary using whatever branch, then use the supplied `/home/ubuntu/gobetween.toml` file. This has all configuration necessary to connect to the supplied LXD server:

```shell
$ sudo ./bin/gobetween -c ~/gobetween.toml
$ curl localhost
```

Please let me know if you have any questions.

**Comment by illarion** [comment]
Sorry, I created duplicate issue without noticing that you've already done whole thing. My bad

**Comment by jtopjian** [comment]
No problem at all. Should I open an Issue+PR next time?

**Comment by illarion** [comment]
I will leave it here just not to forget:

sudo dpkg --add-architecture i386
sudo apt install libacl1-dev:i386
sudo apt install libc-dev:i386

This lines are required in order to make a cross build

**Comment by jtopjian** [comment]
@illarion Good call. I have updated the `deploy.sh` script with that :)

**Comment by illarion** [comment]
Merged

**Pull request closed without merging**
