### PR TITLE
udp: add healthcheck type pingudp and enable access control

### PR DESCRIPTION
**Pull request by yousong**

### CODE REVIEW

**Comment by illarion** [comment]
@yousong could you please add appropriate config example to gobetween.toml (commented and with default values) ?

**Comment by illarion** [comment]
@yousong I have partially merged your PR - commit with adding access control.

**Comment by yousong** [comment]
@illarion 

v2 <- v1

 - Rebased on current master to use net.Addr for udp access control debug logging to align with tcp server.
 - Add pingudp config example to `config/gobetween.toml`
 - Add `toml:` and `json:` tag to `UdpHealthcheckConfig` struct to align with other such code
 - Removed `log.Errorf` on pingudp check failure

A few things I'd like to note here for your consideration.

 - Currently I marked `send` and `receive` as required when kind is `pingudp`.  But the program will segfaul for nil ptr access.  Is this expected and acceptable?
 - I was considering making the `receive` field as a regex field.  It would be more flexible when the on-wire protocol is binary or the content is dynamic.  If you also agree, I will happily switch to that ;)

**Comment by illarion** [comment]
@yousong I've re-implemented this PR in probe-#186 branch with generic support of both tcp and udp probes. Sorry ;) Please take a look, this is what is going to be merged soon. There is no regexp support, but hex support instead, with DNS request/response in example config. Please comment. Thank you.

**Comment by yousong** [comment]
That's better design, thank you.  I am closing this one now.

**Comment by yousong** [comment]
@illarion 

Thank you for the work.  I am afraid that `strconv.Unquote()` call will still be a nuance to work with.  That means users will have to write custom encoding code to make acceptable ProbeSend, ProbeRecv value, compared to using just std encoding from std libraries.

```
buf = bytes.Buffer{}
for _, b := range data {
   if b.isPrintable() {
    buf.Write(b)
  } else {
    buf.Write([]byte(fmt.Printf("\\x%x"), b))
  }
}
```

That `"` in the golang code will then become an internal implementation detail that external programs depends on.

**Comment by illarion** [comment]
@yousong if \xNN doesn't work for you somehow, you can switch to regexp and use it instead

**Comment by illarion** [comment]
@yousong could you please explain in more detail your concern about \xNN representation of binary data?
Here is the test that proves this approach can handle all possible 256 values:

https://play.golang.org/p/rtX7HGcZn1B

**Comment by yousong** [comment]
The first thing is that `strconv.Unquote()` is golang specific.  We can emulate that semantics with another prog lang or our intuition, but it's still golang specific.  That means strictly speaking people will need to learn the details and behaviors of how golang quotes and unquotes strings, then each write their own code to do the encoding/decoding.  If we look at it from this angle, benefit of a widely accepted encoding scheme like base64 should be very clear.

Wrapping up user input with double quotes then feeding that input to `strconv.Unquote()` reminds me of SQL injection.  It just doesn't smell right.

A concrete example.  If I am writing a general API for specifying probe health check method, I will tell my API user to prepare there probe payload as base64 encoded string.  Its common knowledge and there is no need to further specify the quoting rule, no need to craft code for encoding/decoding, no need to differentiate between toml or json.

Hope I am making the point clear.  Sorry if this feels like I am bikeshedding.  But surely it's not a matter of right or wrong, working or not working.  It's just personal perceptions on the issue at hand.  You guys should know this project way better to make the design decision.  Your code, your call ;)

**Comment by illarion** [comment]
Thank you. Your point is clear, but still we're not convinced. Here're some thoughts and comments:

Strictly speaking everything we use in gobetween is golang specific, because it's written in golang.
What users should learn is how to encode hexadecimal values, using \xNN values. 
In case of printable strings, users do not need to encode them, so that "PING\n" or "GET /\n" is valid.
using "\"" smells a bit, but it's not injection - only the admin of gobetween can confiugre it, right? It's not from request or response. It's not API, so the example is out of scope.

**Comment by yousong** [comment]
- gobetween is implemented in golang thus making the implementation golang specific, but user interface (in this case the config) is not
 - yes, that printable characters are directly readable and examined by human eyes is indeed very likely a gain for human admins
 - maybe the possibility of config file being an "API" can be more convincing when someone builds load balancing automation system with gobetween as a component

**Comment by illarion** [comment]
@yousong config file being and API is easy and convenient and bulletproof. If you want expose this fields as base64 -- that's ok, then just decode base64 and encode received bytes as a sequence of \xNN\xMM.. disregarding are these bytes readable or not, it doesn't matter. 

P.S: Is that what your company is providing as a service?

**Comment by nickdoikov** [comment]
@yyyar @illarion @yousong 

I did not see any issue in current (last) Illarion's realization.
For now it is a standard across different LB's, and i`m against creating new bicycles with square wheels instead of using well known working and known design. 

[nginx](https://docs.nginx.com/nginx/admin-guide/load-balancer/udp-health-check/) have almost the  same checks definition :

```
match ntp {
   send \xe3\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00;
   expect ~* \x24;
}
```

**Comment by yyyar** [comment]
Agree on current implementation and config format. Code also looks good.
I think we're good to merge.

**Comment by yousong** [comment]
now all things sorted out, and decision been made, I am closing this pull request now just in case someone may accidently click the merge button here.  Looking forward to the new feature in place.  Thank you

**Comment by yyyar** [comment]
@yousong 
Thank you for your contribution!

**Comment by yousong** [comment]
> @yousong config file being and API is easy and convenient and bulletproof. If you want expose this fields as base64 -- that's ok, then just decode base64 and encode received bytes as a sequence of \xNN\xMM.. disregarding are these bytes readable or not, it doesn't matter.
> 
> P.S: Is that what your company is providing as a service?

it's a multi-cloud management system and LB is one part of the product.  We currently have gobetween as the data plane for UDP transport.  Prior to that I tried keepalived with ipvs which is not fun to work with to put it in a mild way.  The gobetween build is way cleaner.  Thank you again.

**Pull request closed without merging**
