### PR TITLE
add support for Kerberos V5 backend healthcheck

### PR DESCRIPTION
**Pull request by stutiredboy**
```
# # -- krb5 -- #
# kind = "krb5"
# krb5_conf = "/path/to/krb.%host%.conf"	# (required) KRB5_CONFIG for Kerberos Auth, `%host%` will be replaced by backend hostname or ip
# krb5_realm = "CHENXIAOSHENG.COM"		# (required) Kerberos REALM
# krb5_username = "kdc.healthcheck"		# (required) Kerberos Principal
# krb5_keytab = "/path/to/keytab"		# (required) Keytab for Kerberos Principal
#
```

## HealthCheck For KerberosV
 Example for gobetween.toml:
 ```
[servers.krb5]
bind = "0.0.0.0:88"
protocol = "udp"
  [servers.krb5.udp]
  max_responses = 0
  [servers.krb5.discovery]
  kind = "static"
  static_list = [
    "kdc01.chenxiaosheng.com:88",
    "10.176.42.204:88",
  ]
  [servers.krb5.healthcheck]
  kind = "krb5"
  interval = "10s"
  timeout = "5s"
  fails = 2
  passes = 3
  krb5_conf = "/home/gobetween/etc/kdc/krb5.%host%.conf""
  krb5_realm = "CHENXIAOSHENG.COM"
  krb5_username = "kdc.healthcheck"
  krb5_keytab = "/home/gobetween/etc/kdc/kdc.healthcheck.keytab"
```
 ### kind
 For Kerberos/KDC health check, you should use string `krb5` always.
 ### krb5_conf
 [KRB5_CONFIG](http://web.mit.edu/kerberos/krb5-latest/doc/admin/env_variables.html) to check Kerberos/KDC health.
1. The `%host%` will be replaced to backend's hostname or ip address
2. More about kerberos's configure, read [here](http://web.mit.edu/kerberos/krb5-1.12/doc/admin/conf_files/krb5_conf.html) please;
 ### krb5_realm
 [Realm name](http://web.mit.edu/kerberos/krb5-latest/doc/admin/realm_config.html#realm-name)
 ### krb5_username
 [Kerberos Principal](http://web.mit.edu/kerberos/krb5-1.5/krb5-1.5.4/doc/krb5-user/What-is-a-Kerberos-Principal_003f.html)
 ### krb5_keytab
 [The Keytab File](http://web.mit.edu/Kerberos/krb5-1.5/krb5-1.5.3/doc/krb5-install/The-Keytab-File.html)

### CODE REVIEW

**Comment by nickdoikov** [comment]
Please describe your use case .Could you please add step-by step tutorial how to test this (configuration test env, configs etc...).

**Comment by illarion** [comment]
@stutiredboy kerberos seems to be authentication protocol, so how does it match to gobetween use case? Usually gobetween fetches addresses of backend servers from some external source (discovery) and optionally uses that external facilty to check if the backend is alive (healtcheck). 

So, it is not clear what are you trying to do here... please add more info

**Comment by stutiredboy** [comment]
@illarion GoBetween is a excellent load balancer, we use gobetween as our KDC load balancer.(protocol UDP). 

The pull request is only a **healthcheck module** for **KDC backend**. Actually, we can write custom `kinit` script and use `exec` module to reach it, too.

**Comment by shantanugadgil** [comment]
Extending on the above explanation, I can see the value-add for such an approach for **custom protocol healthcheck** for new users.

I know the "exec" health check can be "made to work" for custom protocols by writing our own code/script.

Also, "ping" (tcp connect) can be considered to be adequate for HTTP/HTTPS health of backend.

In a simplistic use case, if the backend check was actually "HTTP(S)" it could be configured for a return value check for success (e.g. 200) and the backend could expose a specific HTTP path (say "/health", which could then emit some useful info)

The same could also be expanded for other things, like say "lxd" (or docker):
i.e. I could use an LXD type of healthcheck to keep a watch on my LXD Server(s) (usually listening on 8443), where gobetween would do an REST API and confirm that the daemon is responding.

Adding @jtopjian for LXD specific thoughts.

Cheers,
Shantanu Gadgil

**Comment by illarion** [comment]
During the initial implementation of UDP in gobetween I was experimenting with custom udp healthchecks, that allowed advanced users to add hex binary snippet of the packet to send and packet to expect, like this:

```
ping = [0x11 0x55 0xFE]
ok = [0x11]
```
but after some research I found that this is not scalable approach, since sometimes there is no response, or it is not possible to write small enough request packet or server responds with too variable packet and a lot of other possible cases.

I would recommend to write custom exec healthchecks for UDP

**Comment by illarion** [comment]
@stutiredboy we've discussed your PR and found it valuable and we would like to have kerberos healthcheck available. But, it doesn't seem that main code base of gobetween would benefit from adding this check, since it is not something generic or common. So, we decided to accept this PR if you will remake it and put the external healthcheck into `gobetween/share/healthcheck/kerberos.sh` and(or) `kerberos.bat` file, so that those who need it could use it, adapt to their usecases and so on.

Is that ok with you? 
Thanks.

**Comment by illarion** [comment]
For now I close it as it is.

**Pull request closed without merging**
