### PR TITLE
[Add] Support for Prometheus Metrics Endpoint

### PR DESCRIPTION
**Pull request by Techcadia**
This Adds a Prometheus Metrics Endpoint at port 9284.

Currently the service would need to be restarted to clear out old metrics. Still not sure how I want to handle the cleanup of that. But this does what we want for our use case.

Always up for Feedback.

### CODE REVIEW

**Comment by Techcadia** [comment]
Techcadia and TechIsCool are the Same Person. Somehow I open this with the wrong account. just going to leave it as is.

**Comment by nickdoikov** [comment]
Thanks,Techcadia  this PR will be reviewed soon.

**Comment by TechIsCool** [comment]
@nickdoikov Any time to review this? Would love to know what you think.

**Comment by illarion** [comment]
@TechIsCool Thank you for your pull request. I've briefly reviewed it and found no visible issues. But in order to merge it, we have to test it. Could you please describe how to setup test environment and use it with your patch?

**Comment by TechIsCool** [comment]
Sure the simplest way to do a test is to just hit the endpoint.
Defaults to http://${hostname}:9284/metrics
This returns a page with all the metrics exposed by the prometheus client lib.

If you want to setup prometheus to query the endpoint. Grabbing the repo and compile the code.

```
go get github.com/prometheus/prometheus
cd $GOPATH/src/github.com/prometheus/prometheus
git checkout v2.2.1
make
mkdir prom_data

cat <<-EOF >> prometheus.yml
scrape_configs:
  - job_name: 'gobetween'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9284']
EOF

./prometheus --config.file=prometheus.yml --storage.tsdb.path=prom_data
```
Prometheus should be running on http://${hostname}:9090
Now you can start gobetween on your localhost as well and metrics should start showing up.


```
# When your done testing cleanup the data dir
rm -r prom_data
```

**Comment by vladzu** [comment]
was this released in 0.6.0 already ?

**Comment by TechIsCool** [comment]
@vladzu currently it is still pending a review from the developers.  If anything needs to be moved forward to support that review I can complete it.

**Comment by ewoutp** [comment]
This seems to be a very relevant addition

**Comment by TechIsCool** [comment]
@illarion I have squashed the commits and remove the version bump.

The global variables in main are actually referenced in the metrics. They can gracefully fail and then they just don't get listed But I found that being able to see what version and commit your on makes life easier when deploying to 60+ servers in a fleet. Currently I have a new custom build in our staging env with this branch as it sits today. I am letting it bake for a few days before pushing it out to production.

It should be noted that I have been running this custom code in production for 5 months and it's been stable. Both Windows and Linux.

**Comment by nickdoikov** [comment]
@illarion @TechIsCool i'm checking and performing load testing  this branch now. Will add conclusion here in few days.

**Comment by Techcadia** [comment]
@nickdoikov @illarion I can push a rebased version that is running off 0.6.1 I have yet to run it in production but am working to promote it forward.

Let me know its the same code just updated to run under the master branch.

**Comment by illarion** [comment]
@Techcadia rebase is not needed, we've already rebased it and put into our production server for testing. Let me check @nickdoikov opinion...

**Comment by illarion** [comment]
Merged to master, thank you!

**Pull request closed without merging**
