### PR TITLE
Typo in startup message

### PR DESCRIPTION
**Pull request by shantanugadgil**
Minor typo in startup message.
(not sure if the same PR got submitted last time?!?)

### CODE REVIEW

**Comment by illarion** [comment]
Dot is not needed here.

**Comment by shantanugadgil** [comment]
@illarion 
Ok about the final full stop.
Could you then just make the spelling correction for the word 'Cloud' ?
It is currently misspelled as 'Cload'

**Comment by illarion** [comment]
My bad.. why you deleted the branch? Now I can't reopen your PR :(

**Comment by shantanugadgil** [comment]
Whoops, I assumed you would make that change from your copy, as my PR had two changes. 👍

**Comment by illarion** [comment]
Ok, I'll just fix typo in master

**Comment by illarion** [comment]
@shantanugadgil fixed in master, thank you

**Pull request closed without merging**
