### PR TITLE
Support to deploy gobetween as Pod in K8s cluster

### PR DESCRIPTION
**Pull request by vishal-yadav**
Adding support to deploy gobetween as Pod/Container in Kubernetes cluster.
**Steps to Launch:**
1. Create ConfigMap **gb** with config gobetween.toml
`$ kubectl create configmap gb --save-config --from-file=<location-of-gobetween.toml> -o yaml | kubectl apply -f -`
2. Launch pod running gobetween container using above ConfigMap
`$ kubectl apply -f gb_k8s_deploy.yaml`

Result/Logs after gobetween is launched.
```
$ kubectl logs gobetween
2019/01/22 10:15:29 gobetween v0.6.1
2019-01-22 10:15:29 [INFO ] (manager): Initializing...
2019-01-22 10:15:29 [INFO ] (api): Starting up API
2019-01-22 10:15:29 [INFO ] (api): Starting HTTP server :8888
2019-01-22 10:15:29 [INFO ] (server): Creating 'sample': 0.0.0.0:3000 weight static none
2019-01-22 10:15:29 [INFO ] (scheduler): Starting scheduler
2019-01-22 10:15:29 [INFO ] (udp/server): Creating UDP server 'udpsample': localhost:4000 weight static none
2019-01-22 10:15:34 [INFO ] (scheduler): Starting scheduler
2019-01-22 10:15:34 [INFO ] (manager): Initialized
```

### CODE REVIEW

**Comment by nickdoikov** [comment]
@vishal-yadav please describe why  it make sense to add this  ? 
From my perspective  appropriate k8s integration is a ingress controller or even load balancer, but not a simple pod.
please add more context about possible use cases .

**Comment by vishal-yadav** [comment]
@nickdoikov, you are right. Need to implement GB ingress controller for integration with K8s. I'll work on it.
Thanks!

**Comment by nickdoikov** [comment]
@vishal-yadav, we are  looking forward to get initial ingress controller implementation form you , thanks.

**Comment by illarion** [comment]
@vishal-yadav is this PR still relevant?

**Pull request closed without merging**
